/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    SearchBox: typeof import('./components/search/SearchBox.vue')['default']
    SearchForm: typeof import('./components/search/SearchForm.vue')['default']
    SearchResultItem: typeof import('./components/search/SearchResultItem.vue')['default']
    SearchResults: typeof import('./components/search/SearchResults.vue')['default']
  }
}
